### ISSUE TITLE
Missing DMenu functions

### ISSUE THREAD

**Issue by GGG-KILLER** [JohnnyCrazy/glua-autocomplete#2]
[DMenu](http://wiki.garrysmod.com/page/Category:DMenu) functions such as `DMenu:AddOption( string label, function OnClick )`, `DMenu:AddSpacer()`, `DMenu:AddSubMenu( string label )` and others are currently missing as of version 0.1.6

**Comment by JohnnyCrazy** [comment]
I will have a look at it when I'm at home :+1:

**Comment by GGG-KILLER** [comment]
Thanks :smile:

**Comment by JohnnyCrazy** [comment]
@GGG-KILLER Fixed in 0.2.0 :+1:
